services:
  diffmvs:
    command: /bin/bash
    stdin_open: true
    tty: true
    build:
      context: ../..
      dockerfile: thirdparty/diffmvs/Dockerfile
    image: 3dgs_pipe:diffmvs
    network_mode: "host"
    shm_size: 8gb
    working_dir: /3dgs_pipe/thirdparty/diffmvs
    environment:
      - SOURCE_FOLDER_PATH=${SOURCE_FOLDER_PATH:-}
    volumes:
      - type: bind
        source: ../..
        target: /3dgs_pipe
      - type: bind
        source: ${TORCH_CACHE_PATH:-../../torch_cache}
        target: /root/.cache
      - type: bind
        source: ${SOURCE_FOLDER_PATH:-../../}
        target: /workspace/source_folder
    gpus:
      - driver: nvidia
        count: all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
